### ISSUE TITLE
resolve codacy issues 

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#257]
Codacy's static code analysis 102 issues, mostly minor and most of them probably easy to solve.

**Comment by GernotMaier** [comment]
Most items are solved with e.g. PR #319.

Remaining issues are attached as screenshot.

- [x] issues in `simtools/config.py` --> will anyway be updated soon with the revision of the config.yml file behaviour; so don't fix
- don't want to fix the enumerate suggestion in the model/camera.py code, seems to be the most efficient solution
- [ ]  TODO: subProcess in simtools/ray_tracing.py, check if this is really needed
- [ ] hesitate to touch anything related to plotting in simtools/visualize.py and simtools/util/legend_handlers.py

![Screenshot 2022-09-09 at 16 03 19](https://user-images.githubusercontent.com/14001688/189368312-92b2498a-33b0-4814-a8e2-879c5e0ee7a2.png)

**Comment by orelgueta** [comment]
I am not sure we can fix the legend and plot1D issues. The former I think must follow a specific format, but I will check. The latter might require too much work to simplify. I will look into it though.

**Comment by orelgueta** [comment]
The legend handlers issue was fixed in #347. The plot1D I am really hesitant to work on, it would simplify a function just to make codacy happy, none of the pieces created would be used anywhere else (for now, if we implement more plotting stuff, then maybe).

**Comment by GernotMaier** [comment]
I think this is fine.

The main remaining issue is the global thing in `config.py`. This should go when improving the configuration (issue #279). After that, we will have 1-3 issue left, which in my opinion is very good.

**Comment by orelgueta** [comment]
OK, so in my mind I am closing this issue.

**Comment by GernotMaier** [comment]
Three issue remaining on codacy, see below.

![Screenshot 2023-11-09 at 10 31 41](https://github.com/gammasim/simtools/assets/14001688/c8880872-d5cf-4ec4-97b4-3a26501d5737)

**Comment by GernotMaier** [comment]
Do think we can close this issue.

- don't think we need / should rewrite the two modules which are apparently too complex
- the subprocess has been discussed in the context of pylint reports and we added a pytlint-disable statement.

@orelgueta - ok to close?
